#!/bin/bash
LAYOUT=$($HOME/.config/xdotool/xkblayout-state/xkblayout-state print " %s (%c)" |grep il |wc -l)
if test $LAYOUT = "1"; then
    $HOME/.config/xdotool/cl.sh
    sleep 0.5
    xdotool type ilanshavit
else
    sleep 0.5
    xdotool type ilanshavit
fi
